version: "3.9"

services:
  app:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: ${APP_NAME:-php_app}_app
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 512M
      PHP_POST_MAX_SIZE: 512M
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
